CIRCUITPY_WIFI_SSID = "ssid_name"
CIRCUITPY_WIFI_PASSWORD = "password"
CIRCUITPY_WEB_INSTANCE_NAME = "LabMonitor"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
CIRCUITPY_WEB_API_PORT=205
sensor1_name="BME280"
sensor1_pins="10,11,8,9"
sensor1_correct_temp="True"
sensor2_name="MAX31865"
sensor2_pins="18,19,16,17"
sensor2_correct_temp="False"
sensor3_name="MCP9808"
sensor3_pins="15,14"
sensor3_correct_temp="False"
mongo_url="https://www.site.com"
mongo_secret_key="very_long_key"
cert_path="/static/cert/cert.pem"
device_name="EnvironmentalChamber"
is_pico_submit_mongo="True"

# Pins format for SPI:
# SCK, MOSI, MISO, OUT
# CLK, SDI, SDO, CS
# CLK, TX, RX, CS

# Pins format for I2C:
# SCL, SDA
