CIRCUITPY_WIFI_SSID = "ssid_name"
CIRCUITPY_WIFI_PASSWORD = "password"
CIRCUITPY_WEB_INSTANCE_NAME = "LabMonitor"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
CIRCUITPY_WEB_API_PORT=205
sensor1 = "BME280"
sensor1Pins = "18,19,16,17"
sensor1CorrectTemp = "True"
sensor2 = "MCP9808"
sensor2Pins = "15,14"
sensor2CorrectTemp = "False"
sensor3 = "MAX31865"
sensor3Pins = "6,7,8,9"
sensor3CorrectTemp = "False"
mongoURL = "https://www.site.com"
mongoSecretKey = "very_long_key"
certPath = "/static/cert/cert.pem"
deviceName = "EnvironmentalChamber"
isPicoSubmitMongo = "False"

# Pins format for SPI:
# SCK, MOSI, MISO, OUT
# CLK, SDI, SDO, CS

# Pins format for I2C:
# SCL, SDA
